export enum StatusEnum {
  SAVED = "SAVED",
  PENDING_APPROVAL = "PENDING APPROVAL",
  EDITED = "EDITED",
  ON_MARKET = "ON MARKET",
  OFF_MARKET = "OFF MARKET",
  SOLD = "SOLD",
  RENTED = "RENTED",
  DELETED = "DELETED",
  DENIED = "DENIED"
}