name: Continuous integration

on:
 push:
 pull_request:
 
jobs:
 Analysis:
   runs-on: ubuntu-latest

   steps:
          
     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v3
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
         fail_ci_if_error: true
         files: ./coverage.opencover.xml