name: E2E Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Create environment file
        env:
          NX_FIREBASE_KEY: ${{ secrets.NX_FIREBASE_KEY }}
          NX_FIREBASE_AUTH_DOMAIN: ${{ secrets.NX_FIREBASE_AUTH_DOMAIN }}}
          NX_FIREBASE_DATABASE_URL: ${{ secrets.NX_FIREBASE_DATABASE_URL }}
          NX_FIREBASE_PROJECT_ID: ${{ secrets.NX_FIREBASE_PROJECT_ID }}}
          NX_FIREBASE_STORAGE_BUCKET: ${{ secrets.NX_FIREBASE_STORAGE_BUCKET }}
          NX_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}}
          NX_FIREBASE_APP_ID: ${{ secrets.NX_FIREBASE_APP_ID }}
          NX_FIREBASE_MEASUREMENT_ID: ${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}
          NX_GOOGLE_MAPS_KEY: ${{ secrets.NX_GOOGLE_MAPS_KEY }}
        run: |
          cat <<EOF > .env.prod
          NX_ENVIRONMENT=production
          NX_USE_EMULATORS=false
          NX_FIREBASE_KEY="$NX_FIREBASE_KEY"
          NX_FIREBASE_AUTH_DOMAIN="$NX_FIREBASE_AUTH_DOMAIN"
          NX_FIREBASE_DATABASE_URL="$NX_FIREBASE_DATABASE_URL"
          NX_FIREBASE_PROJECT_ID="$NX_FIREBASE_PROJECT_ID"
          NX_FIREBASE_STORAGE_BUCKET="$NX_FIREBASE_STORAGE_BUCKET"
          NX_FIREBASE_MESSAGING_SENDER_ID="$NX_FIREBASE_MESSAGING_SENDER_ID"
          NX_FIREBASE_APP_ID="$NX_FIREBASE_APP_ID"
          NX_FIREBASE_MEASUREMENT_ID="$NX_FIREBASE_MEASUREMENT_ID"
          NX_GOOGLE_MAPS_KEY="$NX_GOOGLE_MAPS_KEY"
          EOF
          echo "cat .env.prod"

      - name: Start Application and then Run tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./
          wait-on: 'http://[::1]:4200/'
          install-command: npm install --legacy-peer-deps
          build: npm run build:app:prod
          start: npm run start:app:prod
          command: npx cypress run

      - if: always()
        name: Run Cypress Tests
        uses: actions/upload-artifact@v1
        with:
          name: cypress-videos
          path: cypress/videos