name: Cypress Tests 2

on: push

jobs:
  cypress-run:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:app:dev
          start: npm run start:app:dev
