name: Deploy Angular App

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install
        npm install -g firebase-tools

    - name: Create environment file
      env:
        NX_FIREBASE_KEY: ${{ secrets.NX_FIREBASE_KEY }}
        NX_FIREBASE_AUTH_DOMAIN: ${{ secrets.NX_FIREBASE_AUTH_DOMAIN }}
        NX_FIREBASE_DATABASE_URL: ${{ secrets.NX_FIREBASE_DATABASE_URL }}
        NX_FIREBASE_PROJECT_ID: ${{ secrets.NX_FIREBASE_PROJECT_ID }}
        NX_FIREBASE_STORAGE_BUCKET: ${{ secrets.NX_FIREBASE_STORAGE_BUCKET }}
        NX_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}
        NX_FIREBASE_APP_ID: ${{ secrets.NX_FIREBASE_APP_ID }}
        NX_FIREBASE_MEASUREMENT_ID: ${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}
        NX_GOOGLE_MAPS_KEY: ${{ secrets.NX_GOOGLE_MAPS_KEY }}
      run: |
        cat <<EOF > .env.prod
        NX_ENVIRONMENT=production
        NX_USE_EMULATORS=false
        NX_FIREBASE_KEY="$NX_FIREBASE_KEY"
        NX_FIREBASE_AUTH_DOMAIN="$NX_FIREBASE_AUTH_DOMAIN"
        NX_FIREBASE_DATABASE_URL="$NX_FIREBASE_DATABASE_URL"
        NX_FIREBASE_PROJECT_ID="$NX_FIREBASE_PROJECT_ID"
        NX_FIREBASE_STORAGE_BUCKET="$NX_FIREBASE_STORAGE_BUCKET"
        NX_FIREBASE_MESSAGING_SENDER_ID="$NX_FIREBASE_MESSAGING_SENDER_ID"
        NX_FIREBASE_APP_ID="$NX_FIREBASE_APP_ID"
        NX_FIREBASE_MEASUREMENT_ID="$NX_FIREBASE_MEASUREMENT_ID"
        NX_GOOGLE_MAPS_KEY="$NX_GOOGLE_MAPS_KEY"
        EOF
        echo "cat .env.prod"

    - name: Build Angular app
      run: |
        npm run build:app:prod
        npm run build:api:prod

    - name: Deploy to production
      run: firebase deploy
        