name: k6 Load Tests
on: [push]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install --legacy-peer-deps
      - name: Create env
        env:
          NX_FIREBASE_KEY: ${{ secrets.NX_FIREBASE_KEY }}
          NX_FIREBASE_AUTH_DOMAIN: ${{ secrets.NX_FIREBASE_AUTH_DOMAIN }}}
          NX_FIREBASE_DATABASE_URL: ${{ secrets.NX_FIREBASE_DATABASE_URL }}
          NX_FIREBASE_PROJECT_ID: ${{ secrets.NX_FIREBASE_PROJECT_ID }}}
          NX_FIREBASE_STORAGE_BUCKET: ${{ secrets.NX_FIREBASE_STORAGE_BUCKET }}
          NX_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}}
          NX_FIREBASE_APP_ID: ${{ secrets.NX_FIREBASE_APP_ID }}
          NX_FIREBASE_MEASUREMENT_ID: ${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}
          NX_GOOGLE_MAPS_KEY: ${{ secrets.NX_GOOGLE_MAPS_KEY }}
        run: |
          cat <<EOF > .env.prod
          NX_ENVIRONMENT=production
          NX_USE_EMULATORS=false
          NX_FIREBASE_KEY="$NX_FIREBASE_KEY"
          NX_FIREBASE_AUTH_DOMAIN="$NX_FIREBASE_AUTH_DOMAIN"
          NX_FIREBASE_DATABASE_URL="$NX_FIREBASE_DATABASE_URL"
          NX_FIREBASE_PROJECT_ID="$NX_FIREBASE_PROJECT_ID"
          NX_FIREBASE_STORAGE_BUCKET="$NX_FIREBASE_STORAGE_BUCKET"
          NX_FIREBASE_MESSAGING_SENDER_ID="$NX_FIREBASE_MESSAGING_SENDER_ID"
          NX_FIREBASE_APP_ID="$NX_FIREBASE_APP_ID"
          NX_FIREBASE_MEASUREMENT_ID="$NX_FIREBASE_MEASUREMENT_ID"
          NX_GOOGLE_MAPS_KEY="$NX_GOOGLE_MAPS_KEY"
          EOF
          echo "cat .env.prod"
      - name: Build
        run: |
          npm run build:app:prod 
      - name: Start server and run tests
        run: |
          npm run start:app:dev & npx wait-on http://localhost:4200
          ./k6 run __tests__/k6-loadTest.ts