---
name: Check lint of code before commit
on:
  push:
jobs:
  linting:
    name: Run Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install --legacy-peer-deps --save-dev eslint-config-prettier eslint-plugin-prettier
      - run: npm install -g @ionic/cli
      - name: Run ESLint
        run: npx eslint .
      - name: Build App
        run: ionic build
