---
name: Check lint of code before commit
on:
  push:
jobs:
  linting:
    name: Run Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install --no-package-lock
      - name: Run ESLint
        run: npx eslint .
      - name: Create environment file
        env:
          NX_FIREBASE_KEY: ${{ secrets.NX_FIREBASE_KEY }}
          NX_FIREBASE_AUTH_DOMAIN: ${{ secrets.NX_FIREBASE_AUTH_DOMAIN }}
          NX_FIREBASE_DATABASE_URL: ${{ secrets.NX_FIREBASE_DATABASE_URL }}
          NX_FIREBASE_PROJECT_ID: ${{ secrets.NX_FIREBASE_PROJECT_ID }}
          NX_FIREBASE_STORAGE_BUCKET: ${{ secrets.NX_FIREBASE_STORAGE_BUCKET }}
          NX_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}
          NX_FIREBASE_APP_ID: ${{ secrets.NX_FIREBASE_APP_ID }}
          NX_FIREBASE_MEASUREMENT_ID: ${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}
          NX_GOOGLE_MAPS_KEY: ${{ secrets.NX_GOOGLE_MAPS_KEY }}
          NX_OPEN_AI: ${{ secrets.NX_OPEN_AI }}
          NX_SPAMBOT_ADDRESS: ${{ secrets.NX_SPAMBOT_ADDRESS }}
          NX_SPAMBOT_APP_PASSWORD: ${{ secrets.NX_SPAMBOT_APP_PASSWORD }}
          NX_SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.NX_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
          NX_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.NX_SERVICE_ACCOUNT_PRIVATE_KEY }}
          NX_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.NX_SERVICE_ACCOUNT_CLIENT_EMAIL }}
          NX_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.NX_SERVICE_ACCOUNT_CLIENT_ID }}
          NX_SERVICE_ACCOUNT_CLIENT_CERT_URL: ${{ secrets.NX_SERVICE_ACCOUNT_CLIENT_CERT_URL }}
          NX_SERVICE_ACCOUNT_PROPERTY_ID: ${{ secrets.NX_SERVICE_ACCOUNT_PROPERTY_ID }}
        run: |
          cat <<EOF > .env.prod
          NX_ENVIRONMENT=production
          NX_USE_EMULATORS=false
          NX_FIREBASE_KEY="$NX_FIREBASE_KEY"
          NX_FIREBASE_AUTH_DOMAIN="$NX_FIREBASE_AUTH_DOMAIN"
          NX_FIREBASE_DATABASE_URL="$NX_FIREBASE_DATABASE_URL"
          NX_FIREBASE_PROJECT_ID="$NX_FIREBASE_PROJECT_ID"
          NX_FIREBASE_STORAGE_BUCKET="$NX_FIREBASE_STORAGE_BUCKET"
          NX_FIREBASE_MESSAGING_SENDER_ID="$NX_FIREBASE_MESSAGING_SENDER_ID"
          NX_FIREBASE_APP_ID="$NX_FIREBASE_APP_ID"
          NX_FIREBASE_MEASUREMENT_ID="$NX_FIREBASE_MEASUREMENT_ID"
          NX_GOOGLE_MAPS_KEY="$NX_GOOGLE_MAPS_KEY"
          NX_OPEN_AI: "$NX_OPEN_AI"
          NX_SPAMBOT_ADDRESS: "$NX_SPAMBOT_ADDRESS"
          NX_SPAMBOT_ADDRESS: "$NX_SPAMBOT_APP_PASSWORD"
          EOF
          echo "cat .env.prod"
      - name: Create Service Worker Credential File
        run: |
          mkdir -p ./victorias-secret-google-credentials
          cat <<EOF > ./victorias-secret-google-credentials/homework.json
          {
            "type": "service_account",
            "project_id": "$NX_FIREBASE_PROJECT_ID",
            "private_key_id": "$NX_SERVICE_ACCOUNT_PRIVATE_KEY_ID",
            "private_key": "$NX_SERVICE_ACCOUNT_PRIVATE_KEY",
            "client_email": "$NX_SERVICE_ACCOUNT_CLIENT_EMAIL",
            "client_id": "$NX_SERVICE_ACCOUNT_CLIENT_ID",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "$NX_SERVICE_ACCOUNT_CLIENT_CERT_URL",
            "universe_domain": "googleapis.com",
            "propertyID": "$NX_SERVICE_ACCOUNT_PROPERTY_ID"
          }
          EOF
          echo "cat ./victorias-secret-google-credentials/homework.json"
      - name: Build App
        run: npm run build:app:prod
      - name: Build API
        run: npm run build:api:prod
